Document the Visual Studio Code Extension
Code-Inspect/flowr pull request #710
Opened 2024-03-08 20:18 UTC by EagleoutIce

2024-03-08 20:20 UTC, Ellpeck requested changes

2024-03-08 20:20 UTC, Ellpeck commented on wiki/Overview.md
> +- [*flowR's* Modules](#flowrs-modules)
Shouldn't this be `*flowR*'s`? (also see in the actual heading)

2024-03-08 20:20 UTC, Ellpeck commented on README.md
> +To get started with _flowR_, please check out the [Overview](https://github.com/Code-Inspect/flowr/wiki/Overview). The [Setup](https://github.com/Code-Inspect/flowr/wiki/Setup) wiki page explains how
Vor

2024-03-08 20:25 UTC, Ellpeck approved these changes

2024-03-08 20:28 UTC, merged

2024-03-17 21:27 UTC, EagleoutIce commented
_This pull request is included in v1.4.2 (see [Release v1.4.2 (Dropping xmlparsedata, Benchmark Re-Runs, and Repl Fixes)](https://github.com/Code-Inspect/flowr/releases/tag/v1.4.2))._